"""Writes enclosure/logo.scad: the brain-drain logo (docs/img/logo.svg) as a 2D OpenSCAD module for engraving into the lid.

    python3 tools/gen_logo.py

logo2d() is in SVG pixels with y up, centred on the middle of the artwork (about 1054 x 506 units). Recessed areas are the
brain, the tentacles and the drive icons; the fissure, folds, eye whites, and the drive platters stay raised, the pupils are
recessed again. shell.scad scales it to the lid.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "hardware" / "tools"))
import logo_geom  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "logo.scad"


def pts(p, cx, cy):
    return "[" + ",".join(f"[{x - cx:.1f},{-(y - cy):.1f}]" for x, y in p) + "]"


def main():
    g = logo_geom.load()
    x0, y0, x1, y1 = g.bbox
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    bx, by, brx, bry = g.brain
    L = ["// GENERATED by enclosure/tools/gen_logo.py from docs/img/logo.svg -- do not edit",
         f"logo_w = {x1 - x0:.1f};   // artwork size in logo units",
         f"logo_h = {y1 - y0:.1f};",
         "module stroke(p, w) { for (i = [0 : len(p) - 2]) hull() { translate(p[i]) circle(d = w, $fn = 14); translate(p[i + 1]) circle(d = w, $fn = 14); } }",
         "tentacles = [" + ",\n  ".join(pts(t, cx, cy) for t in g.tentacles) + "];",
         "folds = [" + ",\n  ".join(pts(t, cx, cy) for t in g.gyri) + "];",
         f"brain = [{bx - cx:.1f}, {-(by - cy):.1f}, {brx}, {bry}];",
         "eyes = [" + ", ".join(f"[{e[0] - cx:.1f},{-(e[1] - cy):.1f},{e[2]},{e[3]},{e[4] - cx:.1f},{-(e[5] - cy):.1f},{e[6]}]" for e in g.eyes) + "];",
         "drives = [" + ", ".join(f"[{x - cx:.1f},{-(y - cy) - 60:.1f}]" for x, y in g.hdds) + "];   // lower-left corner of each 92 x 60 icon",
         "module drive_icon() {",
         "    difference() {",
         "        translate([0, 0]) offset(r = 6) offset(delta = -6) square([92, 60]);",
         "        // raised: the platter ring, the three bars and the spindle arm",
         "        translate([34, 30]) difference() { circle(r = 20, $fn = 32); circle(r = 14, $fn = 32); }",
         "        for (k = [14, 26, 38]) translate([60, 60 - k - 6]) square([22, 6]);",
         "    }",
         "}",
         "module logo2d() {",
         "    union() {",
         "        difference() {",
         "            union() {",
         "                translate([brain[0], brain[1]]) scale([brain[2], brain[3]]) circle(r = 1, $fn = 96);",
         "                for (t = tentacles) stroke(t, 34);",
         "                for (d = drives) translate(d) drive_icon();",
         "            }",
         "            // raised inside the brain: the fissure and the folds, the eye whites",
         "            for (f = folds) stroke(f, 9);",
         "            for (e = eyes) translate([e[0], e[1]]) scale([e[2], e[3]]) circle(r = 1, $fn = 32);",
         "        }",
         "        for (e = eyes) translate([e[4], e[5]]) circle(r = e[6], $fn = 24);   // pupils",
         "    }",
         "}"]
    OUT.write_text("\n".join(L) + "\n")
    print("wrote", OUT, f"({x1 - x0:.0f} x {y1 - y0:.0f} units)")


main()
