"""Read hardware/brain-drain.kicad_pcb and emit enclosure/board.scad.

board.scad holds the board size, the mounting holes, and every feature the
enclosure must cut or clear, in board coordinates: x from the left edge, y from
the REAR edge (the edge all cables leave through), z up from the board top.
Run from enclosure/:  python3 tools/kicad_to_scad.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "hardware" / "tools"))
import sexp  # noqa: E402

PCB = ROOT / "hardware" / "brain-drain.kicad_pcb"
OUT = ROOT / "enclosure" / "board.scad"

# reference -> (kind, width, height_above_board, z_offset, note). Sizes are the
# physical part face the enclosure must clear, before clearance is added.
FEATURES = {
    "J21": ("rear", 17.0, 16.0, 0.0, "DIN power jack face (Kycon: 16 wide, ~15 tall)"),
    "J4":  ("rear", 16.5, 13.5, 0.0, "RJ45 magjack"),
    "J5":  ("rear", 9.5, 3.6, 0.9, "USB-C receptacle"),
    "J10": ("rear", 28.0, 9.0, 0.0, "SATA 22-pin receptacle, bay 1"),
    "J11": ("rear", 28.0, 9.0, 0.0, "SATA 22-pin receptacle, bay 2"),
    "J12": ("rear", 28.0, 9.0, 0.0, "SATA 22-pin receptacle, bay 3"),
    "J13": ("rear", 28.0, 9.0, 0.0, "SATA 22-pin receptacle, bay 4"),
    "J3":  ("left", 15.0, 3.0, 0.0, "microSD card slot"),
    "SW1": ("top", 23.0, 11.0, 0.0, "8-way DIP switch slot"),
    "J41": ("top", 30.0, 30.0, 0.0, "OLED module window region (module is lid-mounted, header J41 below)"),
    "D1":  ("led", 3.2, 0, 0, "power LED"), "D2": ("led", 3.2, 0, 0, "activity LED"), "D3": ("led", 3.2, 0, 0, "status LED"),
    "D10": ("led", 3.2, 0, 0, "bay 1 LED"), "D11": ("led", 3.2, 0, 0, "bay 2 LED"), "D12": ("led", 3.2, 0, 0, "bay 3 LED"),
    "D13": ("led", 3.2, 0, 0, "bay 4 LED"), "D50": ("led", 3.2, 0, 0, "M.2 LED"),
    "M1":  ("cm5", 40.0, 55.0, 0, "CM5 module (origin = MH1 hole)"),
    "J50": ("m2", 22.0, 80.0, 0, "M.2 socket; module runs toward +x"),
    "SW3": ("door", 0, 0, 0, "M.2 door microswitch"),
    "J40": ("top", 10.0, 5.0, 0, "fan header"),
}


def main():
    tree = sexp.parse(PCB.read_text())[0]
    # outline from Edge.Cuts lines/arcs
    xs, ys = [], []
    for tag in ("gr_line", "gr_arc"):
        for g in sexp.find_all(tree, tag):
            if str(sexp.find(g, "layer")[1]) != "Edge.Cuts":
                continue
            for pt in ("start", "end", "mid"):
                n = sexp.find(g, pt)
                if n:
                    xs.append(float(n[1])); ys.append(float(n[2]))
    ox, oy = min(xs), min(ys)
    bw, bh = max(xs) - ox, max(ys) - oy
    feats, holes = [], []
    for fp in sexp.find_all(tree, "footprint"):
        ref = next((str(p[2]) for p in sexp.find_all(fp, "property") if str(p[1]) == "Reference"), "")
        at = sexp.find(fp, "at")
        x, y = float(at[1]) - ox, float(at[2]) - oy
        rot = float(at[3]) if len(at) > 3 else 0.0
        if ref.startswith("H") and ref[1:].isdigit():
            holes.append((ref, x, y))
        elif ref in FEATURES:
            kind, w, h, z, note = FEATURES[ref]
            feats.append((ref, kind, x, y, rot, w, h, z, note))
    lines = ["// GENERATED by enclosure/tools/kicad_to_scad.py from hardware/brain-drain.kicad_pcb — do not edit",
             f"board_w = {bw:.2f};", f"board_h = {bh:.2f};",
             "// mounting holes [x, y]",
             "board_holes = [" + ", ".join(f"[{x:.2f}, {y:.2f}]" for _, x, y in holes) + "];",
             "// features: [ref, kind, x, y, rot, w, h, z]  (kinds: rear left top led cm5 m2 door)",
             "board_features = ["]
    for ref, kind, x, y, rot, w, h, z, note in feats:
        lines.append(f'  ["{ref}", "{kind}", {x:.2f}, {y:.2f}, {rot:.0f}, {w:.2f}, {h:.2f}, {z:.2f}],  // {note}')
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: board {bw:.1f} x {bh:.1f}, {len(holes)} holes, {len(feats)} features")


if __name__ == "__main__":
    main()
